title: 环境学院
author: Mr.Hope
time: 2020 年 9 月 1 日
content:
  - tag: account
    name: 环境学院
    logo: $img/media/environment.png
    detail: NENU 环境学院
    wxid: dongshihuanjing
    wxcode: $img/media/environment-wechat.jpg
    account: environment
    location:
      latitude: 43.825102
      longitude: 125.426706
    site: https://hjxy.nenu.edu.cn

  - tag: list
    items:
      - text: 学院简介
        icon: about
        path: /intro/school/environment/intro

      - text: 专业介绍
        icon: intro
        path: /intro/school/environment/enroll

      - text: 科研平台
        icon: platform
        path: /intro/school/environment/platform

      - text: 实验教学示范中心
        icon: degree
        path: /intro/school/environment/teach

      - text: 实验中心
        icon: experiment
        path: /intro/school/environment/experiment
