title: é¦–é¡µ
id: main
grey: true
hidden: true
content:
  - tag: title
    text: æ­¤å¤„æœ‰æœç´¢ğŸ‘† æ‚¨å¯ä»¥å¯¹å°ç¨‹åºå†…å®¹è¿›è¡ŒæŸ¥æ‰¾

  - tag: list
    header: ä½¿ç”¨å¿…è¯»
    content:
      - text: å°ç¨‹åºä½¿ç”¨é¡»çŸ¥
        icon: about
        url: page?path=other/about/guide

  - tag: grid
    header: æ‚¨å¯èƒ½æƒ³å…³æ³¨
    content:
      - text: å½•å–æŸ¥è¯¢
        color: orange
        name: Search
        icon: search
        path: intro/enroll/search

      - text: æ–°ç”Ÿå…¥å­¦æ•™è‚²
        color: blue
        name: Course
        icon: study
        path: guide/yiban/

      - text: æ¯æ—¥å¥åº·ä¸ŠæŠ¥
        color: purple
        name: Report
        icon: apply
        path: guide/epidemic/miniprogram/

      - text: å…¥å­¦å‡†å¤‡
        color: red
        name: Prepare
        icon: prepare
        path: guide/prepare/

      - text: ä¸“ä¸šä»‹ç»
        color: olive
        name: Major
        icon: about
        path: intro/school/major

      - text: å­¦æ ¡ä»‹ç»
        color: mauve
        name: Intro
        icon: about
        path: intro/about/

      - text: è½¬ä¸“ä¸š
        color: orange
        name: Change Major
        icon: change
        path: guide/change-major/

      - text: å­¦ä½
        color: blue
        name: Degree
        icon: degree
        path: guide/degree/

      - text: æ–°ç”Ÿç¾¤
        color: purple
        name: QQ Group
        icon: qq-group
        path: guide/prepare/qq-group/

      - text: è°¨é˜²è¯ˆéª—
        color: blue
        name: Protection
        icon: alert
        path: guide/prepare/cheat

      - text: å¯å®¤
        color: grey
        name: Dorm
        icon: dorm
        path: guide/dorm/

      - text: é£Ÿå ‚
        color: mauve
        name: Dining
        icon: dining
        path: guide/dining/

    footer: æ›´å¤šå†…å®¹è¯·è¯¦è§ä¸‹æ–¹å…¶ä»– Tab é¡µ

  - tag: text
    heading: " "
    text: "   å¦‚æœæ‚¨è¿˜æœ‰ä»€ä¹ˆç–‘é—®ï¼Œæ¬¢è¿åŠ å…¥ in ä¸œå¸ˆå’¨è¯¢ç¾¤ (1139044856) è¿›è¡Œå’¨è¯¢ã€‚\n   å°ç¨‹åºéƒ½æ˜¯ Mr.Hope ä¸ªäººå¼€å‘ç¼–å†™ï¼Œç°å·²èŠ±è´¹ Mr.Hope è¶… 2000 å°æ—¶ï¼Œæ–‡å­—æ•°é‡è¶…è¿‡ 39 ä¸‡å­—ï¼ŒåŒæ—¶å°ç¨‹åºæœåŠ¡å™¨æ¯å¹´ä¼šäº§ç”Ÿå¼€é”€ã€‚å¦‚æœæ‚¨è§‰å¾—å°ç¨‹åºå¾ˆæœ‰å¸®åŠ©ï¼Œæ¬¢è¿æ‚¨ç»™äºˆæ”¯æŒã€‚"
    style:
      color: "#888"
      font-size: 14px

  - tag: advanced-list
    header: false
    content:
      - text: åŠ å…¥ in ä¸œå¸ˆå’¨è¯¢ç¾¤
        icon: qq-group
        type: button
        openType: openGroupProfile
        groupId: "1139044856"

      - text: è”ç³» Mr.Hope
        icon: contact
        type: button
        openType: addFriend
        openId: 868D7B2F0C609B4285698EAB77A47BA1
    footer: " "
