- tag: list
  header: 近期更新
  content:
    - text: |-
        V 4.1.0:
        · 重构 Tab 页 UI
        · 优化分享逻辑

    - text: |-
        V 4.0.0:
        · 重构底层，进一步提升性能

    - text: |-
        V 3.8.0:
        · 添加容器组件
        · 重构地图UI

    - text: |-
        V 3.7.0:
        · 重构资源更新逻辑

    - text: |-
        V 3.6.0:
        · 图标支持热更新

    - text: |-
        V 3.5.0:
        · 添加了复制组件
        · 添加了添加好友、加群、发送到桌面等快捷功能(仅QQ)
        · 添加了二维码(仅QQ)
        · 添加了版权说明

    - text: |-
        V 3.4.0:
        · 添加了东师介绍板块
        · 对搜索功能进行了增强

    - text: |-
        V 3.3.0:
        小程序现在支持全文搜索

    - text: |-
        V 3.2.0:
        添加校园公众号

    - text: |-
        V 3.1.0:
        重构播放器
        · 解决被系统中断后无法播放的问题
        · 添加歌词

    - text: |-
        V 3.0.0:
        重构 UI，小程序整体表现更加精致
        · 适配微信暗黑模式
        · 改善小程序底层，降低小程序内存占用

    - text: 查看详细日志
      url: page?path=other/log/index
