title: é¦–é¡µ
id: main
grey: true
hidden: true
content:
  # - tag: title
  #   text: å¸Œæœ›å·¥ä½œå®¤é•¿æœŸæ‹›æ–°

  # - tag: list
  #   header: false
  #   content:
  #     - text: æ‹›æ–°è¯¦æƒ…
  #       url: page?path=other/hope-studio/invite

  - tag: title
    text: æ­¤å¤„æœ‰æœç´¢ğŸ‘† æ‚¨å¯ä»¥å¯¹å°ç¨‹åºå†…å®¹è¿›è¡ŒæŸ¥æ‰¾

  - tag: text
    type: danger
    heading: è¯·å„ä½ç ”ç©¶ç”Ÿæ³¨æ„
    text:
      - æœ¬å°ç¨‹åºæ˜¯ Mr.Hope çš„ä¸ªäººåˆ¶ä½œï¼Œå±äºå…¬ç›ŠæœåŠ¡ã€‚
      - å„ä½éƒ½å·²ç»è¯»è¿‡4å¹´çš„æœ¬ç§‘çš„æˆå¹´äººäº†ï¼Œæ‰€ä»¥æˆ‘ä¸ä¼šå°†è¯¸ä½å½“å°å­©å­æƒ¯ç€ã€‚
      - è¯·ä¸è¦è¿‡æ¥æŠŠæˆ‘å½“å­¦æ ¡éª‚ï¼Œå¦åˆ™æˆ‘ä¼šéª‚å›å»ï¼‹æ‹‰é»‘!
      - è¯·ä¸è¦æ‘†å‡ºä¸€å‰¯è‡­è„¸åƒæˆ‘æ¬ ä½ é’±ä¸€æ ·ï¼Œå¦åˆ™æˆ‘ä¹Ÿä¸ä¼šæ­ç†ä½ ç›´æ¥æ‹‰é»‘!
      - æˆ‘å¾ˆå¿™ï¼Œæˆ‘ä¹Ÿæœ‰è‡ªå·±çš„äº‹æƒ…è¦åšï¼Œæé—®ä¹‹å‰å…ˆæœç´¢å°ç¨‹åºï¼Œå·²æœ‰çš„å†…å®¹æˆ‘ä¸ä¼šè¿›è¡Œè§£ç­”ã€‚å¦å¤–æˆ‘ä¸ä¿è¯å›å¤çš„æ—¶æ•ˆï¼Œæˆ‘æœ‰ç©ºçš„æ—¶å€™è‡ªç„¶ä¼šå›ã€‚
      - å¦‚æœä½ ç¡®å®šä½ çš„é—®é¢˜æ— æ³•é€šè¿‡å°ç¨‹åºè§£å†³ï¼Œæ¬¢è¿é€šè¿‡ä¸‹æ–¹æŒ‰é’®å’¨è¯¢æˆ‘ã€‚

  - tag: advanced-list
    header: false
    content:
      - text: è”ç³» Mr.Hope
        icon: contact
        type: button
        openType: contact

  - tag: list
    header: ä½¿ç”¨å¿…è¯»
    content:
      - text: å°ç¨‹åºä½¿ç”¨é¡»çŸ¥
        icon: about
        url: page?path=other/about/guide

      - text: å¸¸è§é—®é¢˜
        icon: faq
        path: guide/faq/

  - tag: grid
    header: æ‚¨å¯èƒ½æƒ³å…³æ³¨
    content:
      - text: åˆ°æ ¡è·¯çº¿
        color: grey
        name: Arrival
        icon: locate
        path: /guide/arrival/

      - text: æ–°ç”ŸæŠ¥åˆ°
        color: orange
        name: Check
        icon: check
        path: guide/check/

      - text: å¿«é€’
        color: mauve
        name: Express
        icon: express
        path: guide/express/

      - text: å¯å®¤
        color: grey
        name: Dorm
        icon: dorm
        path: guide/dorm/

      - text: é£Ÿå ‚
        color: mauve
        name: Dining
        icon: dining
        path: guide/dining/

      - text: è¶…å¸‚
        color: olive
        name: Shop
        icon: shop
        path: guide/shop/

      - text: æ´—æµ´
        color: red
        name: Bath
        icon: bath
        path: guide/bath/

      - text: ç”Ÿæ´»
        color: purple
        name: Life
        icon: life
        path: guide/life/

      - text: è´¦æˆ·
        color: blue
        name: Account
        icon: authorize
        path: guide/account/

      - text: æ ¡å›­å¡
        color: red
        name: Card
        icon: card
        path: guide/card/

      - text: æ ¡å›­ç½‘
        color: purple
        name: Network
        icon: network
        path: guide/network/

      - text: é€‰è¯¾
        color: cyan
        name: Select
        icon: select
        path: guide/select/

      # - text: ç–«æƒ…ç›¸å…³
      #   color: mauve
      #   name: Epidemic
      #   icon: virus
      #   path: guide/epidemic/

      # - text: æ¯æ—¥å¥åº·ä¸ŠæŠ¥
      #   color: purple
      #   name: Report
      #   icon: apply
      #   path: guide/epidemic/miniprogram/

      # - text: å…¥å­¦å‡†å¤‡
      #   color: red
      #   name: Prepare
      #   icon: prepare
      #   path: guide/prepare/

      # - text: éœ€å¸¦ç‰©å“
      #   color: olive
      #   name: Necessity
      #   icon: necessity
      #   path: guide/necessity/

      # - text: ä¸“ä¸šä»‹ç»
      #   color: olive
      #   name: Major
      #   icon: about
      #   path: intro/school/major

      # - text: å­¦æ ¡ä»‹ç»
      #   color: mauve
      #   name: Intro
      #   icon: about
      #   path: intro/about/

      # - text: è½¬ä¸“ä¸š
      #   color: orange
      #   name: Change Major
      #   icon: change
      #   path: guide/change-major/

      # - text: å­¦ä½
      #   color: blue
      #   name: Degree
      #   icon: degree
      #   path: guide/degree/

      # - text: æ–°ç”Ÿç¾¤
      #   color: purple
      #   name: QQ Group
      #   icon: qq-group
      #   path: guide/prepare/qq-group/

      # - text: è°¨é˜²è¯ˆéª—
      #   color: blue
      #   name: Protection
      #   icon: alert
      #   path: guide/prepare/cheat

    footer: æ›´å¤šå†…å®¹è¯·è¯¦è§ä¸‹æ–¹å…¶ä»– Tab é¡µ

  # - tag: text
  #   type: danger
  #   heading: è¯·å„ä½ç ”ç©¶ç”Ÿæ–°ç”Ÿæ³¨æ„
  #   text:
  #     - æœ¬å°ç¨‹åºæ˜¯ Mr.Hope çš„ä¸ªäººåˆ¶ä½œï¼Œå±äºå…¬ç›ŠæœåŠ¡ã€‚
  #     - å„ä½éƒ½å·²ç»è¯»è¿‡4å¹´çš„æœ¬ç§‘çš„æˆå¹´äººäº†ï¼Œæ‰€ä»¥æˆ‘ä¸ä¼šå°†è¯¸ä½å½“å°å­©å­æƒ¯ç€ã€‚
  #     - è¯·ä¸è¦è¿‡æ¥æŠŠæˆ‘å½“å­¦æ ¡éª‚ï¼Œå¦åˆ™æˆ‘ä¼šéª‚å›å»ï¼‹æ‹‰é»‘!
  #     - è¯·ä¸è¦æ‘†å‡ºä¸€å‰¯è‡­è„¸åƒæˆ‘æ¬ ä½ é’±ä¸€æ ·ï¼Œå¦åˆ™æˆ‘ä¹Ÿä¸ä¼šæ­ç†ä½ ç›´æ¥æ‹‰é»‘!
  #     - æˆ‘å¾ˆå¿™ï¼Œæˆ‘ä¹Ÿæœ‰è‡ªå·±çš„äº‹æƒ…è¦åšï¼Œæé—®ä¹‹å‰å…ˆæœç´¢å°ç¨‹åºï¼Œå·²æœ‰çš„å†…å®¹æˆ‘ä¸ä¼šè¿›è¡Œè§£ç­”ã€‚å¦å¤–æˆ‘ä¸ä¿è¯å›å¤çš„æ—¶æ•ˆï¼Œæˆ‘æœ‰ç©ºçš„æ—¶å€™è‡ªç„¶ä¼šå›ã€‚

  # - tag: text
  #   text:
  #     - å¦‚æœä½ çš„é—®é¢˜æ²¡èƒ½é€šè¿‡å°ç¨‹åºè§£å†³ï¼Œæ¬¢è¿é€šè¿‡ä¸‹æ–¹æŒ‰é’®å’¨è¯¢æˆ‘ã€‚

  # - tag: advanced-list
  #   header: false
  #   content:
  #     - text: è”ç³» Mr.Hope
  #       icon: contact
  #       type: button
  #       openType: contact
