title: é¦–é¡µ
id: main
grey: true
hidden: true
content:
  # - tag: title
  #   text: å¸Œæœ›å·¥ä½œå®¤é•¿æœŸæ‹›æ–°

  # - tag: list
  #   header: false
  #   items:
  #     - text: æ‹›æ–°è¯¦æƒ…
  #       url: page?path=other/hope-studio/invite

  # - tag: title
  #   text: æ­¤å¤„æœ‰æœç´¢ğŸ‘† æ‚¨å¯ä»¥å¯¹å°ç¨‹åºå†…å®¹è¿›è¡ŒæŸ¥æ‰¾

  - tag: text
    type: info
    heading: 2021å¹´ä¸‹åŠå¹´å››å…­çº§è€ƒè¯•æ—¶é—´
    text:
      - è‹±è¯­å››çº§å£è¯­è€ƒè¯•è€ƒè¯•æ—¶é—´ä¸º11æœˆ21æ—¥
      - è‹±è¯­å…­çº§å£è¯­è€ƒè¯•è€ƒè¯•æ—¶é—´ä¸º11æœˆ22æ—¥
      - è‹±è¯­å››çº§ç¬”è¯•è€ƒè¯•è€ƒè¯•æ—¶é—´ä¸º12æœˆ18æ—¥ 9:00 - 11:20
      - è‹±è¯­å…­çº§ç¬”è¯•è€ƒè¯•è€ƒè¯•æ—¶é—´ä¸º12æœˆ18æ—¥ 15:00 - 17:25

  - tag: grid
    header: æ‚¨å¯èƒ½æƒ³å…³æ³¨
    items:
      - text: å››å…­çº§
        color: red
        name: CET
        icon: cet
        path: guide/exam/cet/

      - text: é€‰è¯¾
        color: cyan
        name: Select
        icon: select
        path: guide/select/

      - text: ä½¿ç”¨ IE å†…æ ¸
        color: olive
        name: IE
        icon: ie
        path: guide/tip/ie/

      - text: è¯¾ç¨‹
        color: orange
        name: Course
        icon: content
        path: guide/course/

      - text: æ•™åŠ¡ç³»ç»Ÿ
        color: red
        name: System
        icon: system
        path: guide/system/

      - text: è´¦æˆ·
        color: blue
        name: Account
        icon: authorize
        path: guide/account/

      - text: æ ¡å†
        color: mauve
        name: Calendar
        icon: calendar
        url: calendar

      - text: ç”Ÿæ´»
        color: olive
        name: Life
        icon: life
        path: guide/life/

      - text: å¸¸è§æœåŠ¡
        color: mauve
        name: Service
        icon: service
        path: guide/action/

      - text: è½¬ä¸“ä¸š
        color: red
        name: Change Major
        icon: change
        path: guide/change-major/

      - text: å­¦ä¹ 
        color: mauve
        name: Study
        icon: study
        path: guide/study/

      - text: å›¾ä¹¦é¦†
        color: blue
        name: Library
        icon: library
        path: intro/apt/library/

      - text: æ ¡å†…è€ƒè¯•
        color: olive
        name: Test
        icon: test
        path: guide/test/

    footer: æ›´å¤šå†…å®¹è¯·è¯¦è§ä¸‹æ–¹å…¶ä»– Tab é¡µ

  - tag: card
    cover: http://mmbiz.qpic.cn/mmbiz_jpg/ic9k8LCTbicc7fibAYDFBn7oAvOaEs00iblrOKaFWoIrqzQzoXXDPmHNjS9bm9ZUVQWB3149EYsjmQNS4jU1HzUW5Q/0?wx_fmt=jpeg
    title: æ‹›çº³å°ç¨‹åºå¿—æ„¿è€…
    logo: $img/inNENU.png
    name: inä¸œå¸ˆ
    url: page?path=other/guide/volunteer
