title: 首页
id: main
grey: true
hidden: true
content:
  - tag: card
    cover: $img/tab/yiban.jpg
    title: 入学教育课程
    desc: 入学教育课程现已开放
    logo: study
    url: info?id=Gyiban/

  - tag: list
    items:
      - text: 经验分享直播与答疑
        icon: activity
        url: info?path=OMrHope/streaming

      - text: 报到时间
        icon: time
        path: guide/check/location-and-time

      - text: 找到组织
        icon: qq-group
        path: guide/contact/

  - tag: grid
    header: 您可能想关注
    items:
      - text: 录取查询
        color: purple
        name: Admission
        icon: letter
        url: admission?type=search

      - text: 入学准备
        color: red
        name: Prepare
        icon: prepare
        path: guide/prepare/

      - text: 需带物品
        color: olive
        name: Necessity
        icon: necessity
        path: guide/necessity/

      - text: 寝室
        color: blue
        name: Dorm
        icon: dorm
        path: guide/dorm/

      - text: 食堂
        color: orange
        name: Dining
        icon: dining
        path: guide/dining/

      - text: 快递
        color: mauve
        name: Express
        icon: express
        path: guide/express/

      - text: 超市
        color: olive
        name: Shop
        icon: shop
        path: guide/shop/

      - text: 洗浴
        color: red
        name: Bath
        icon: bath
        path: guide/bath/

      - text: 社团
        color: orange
        name: Association
        icon: association
        path: guide/association/

      - text: 校园卡
        color: red
        name: Card
        icon: card
        path: guide/card/

      - text: 校园网
        color: purple
        name: Network
        icon: network
        path: guide/network/

      - text: 生活
        color: purple
        name: Life
        icon: life
        path: guide/life/

      - text: 专业介绍
        color: olive
        name: Major
        icon: about
        path: intro/school/major

      - text: 转专业
        color: red
        name: Change Major
        icon: change
        path: guide/change-major/

      - text: 师范生
        color: purple
        name: Normal
        icon: teacher
        path: guide/normal/

      - text: 课程
        color: orange
        name: Course
        icon: content
        path: guide/course/

      - text: 学习
        color: mauve
        name: Study
        icon: study
        path: guide/study/

      - text: 图书馆
        color: blue
        name: Library
        icon: library
        path: intro/apt/library/

      - text: 校历
        color: mauve
        name: Calendar
        icon: calendar
        url: calendar

    footer: 更多内容请详见下方其他 Tab 页

  - tag: card
    cover: $img/tab/faq.png
    title: 常见问题
    logo: faq
    url: info?id=Gfaq/

  # - tag: card
  #   cover: http://mmbiz.qpic.cn/mmbiz_jpg/ic9k8LCTbicc7fibAYDFBn7oAvOaEs00iblrOKaFWoIrqzQzoXXDPmHNjS9bm9ZUVQWB3149EYsjmQNS4jU1HzUW5Q/0?wx_fmt=jpeg
  #   title: 招纳小程序志愿者
  #   logo: $img/inNENU.png
  #   name: in 东师
  #   url: info?path=Oguide/volunteer
