name: NENU 环境学院
detail: 东北师范大学环境学院
desc: 了解更多东师环境学院的信息与活动
id: dongshihuanjing
logo: $img/media/environment.png
qrcode: $img/media/environment-wechat.jpg
article:
  - cover: http://mmbiz.qpic.cn/mmbiz_jpg/IiaBlQyAP0uEKW4cED0zSicAAgp8PSiantEBq76Dg2885j1v268hE5MxmYX5nSKro8icial2wjQmowmsIvBU8KWrjZA/0?wx_fmt=jpeg
    title: 环境学院经典阅读分享会(第一期)成功举办
    url: https://mp.weixin.qq.com/s/dKbJxiATy9xDdMi5Z2l3dg

  - cover: http://mmbiz.qpic.cn/mmbiz_jpg/IiaBlQyAP0uEKW4cED0zSicAAgp8PSiantEBpricEkomax1yDayiaqwdHobhzSfOibsaBlz8XxVhCsQmefuibu2YL75Pg/0?wx_fmt=jpeg
    title: 科研达人成长训练营之 2021 年秋季学期“求是创新”学术沙龙(第Ⅰ期)成功举办
    url: https://mp.weixin.qq.com/s/33PXsnD-g3KnrPOAtmvq_g

  - cover: http://mmbiz.qpic.cn/mmbiz_jpg/IiaBlQyAP0uEPFEBJdKqEiakbGfbAZXC8pbib2tILlcKk6NH4TrHD3G1a2wxPMU2GIeyZQyQgwcbhfIwCfnzfwcAw/0?wx_fmt=jpeg
    title: 环境学院 2022 年度本科生科研立项评审会成功召开
    url: https://mp.weixin.qq.com/s/QGlwr1fkM6vR7dXH32y1kQ

  - cover: http://mmbiz.qpic.cn/mmbiz_jpg/IiaBlQyAP0uEPFEBJdKqEiakbGfbAZXC8pibDcIokBWynAae8MGU0btMfw3CAwWcQQGGBlZbnQwxialuHP2IRxibiaDw/0?wx_fmt=jpeg
    title: 环境学院举办长春市市政工程设计研究院校园宣讲会
    url: https://mp.weixin.qq.com/s/LFgUgR00rMs7JwvfggMGIQ

  - cover: http://mmbiz.qpic.cn/mmbiz_jpg/IiaBlQyAP0uGBib6QM9iauNXUpCtibWIxicPbXM4WHNL2V3Iic65QMxgJictt1dXJJp1WNdHpkJoyIQTBQicib6acELVTxA/0?wx_fmt=jpeg
    title: 环境学院举办 2021 年秋季学期团校暨团学骨干素质提升工程(第二期)
    url: https://mp.weixin.qq.com/s/1kORU5HIzUFQkCCLc2Ntrg

  - cover: http://mmbiz.qpic.cn/mmbiz_jpg/IiaBlQyAP0uGBib6QM9iauNXUpCtibWIxicPbibNicYJh13EsIXN11Biao7zAzuDXodydjiaw4tt6lXaqMXTx0Pn5cGiaQag/0?wx_fmt=jpeg
    title: 环境学院举办 2021 年秋季学期团校暨团学骨干素质提升工程(第三期)
    url: https://mp.weixin.qq.com/s/Cy4xr2PGhjvhAm2DFh3a4Q

  - cover: http://mmbiz.qpic.cn/mmbiz_jpg/IiaBlQyAP0uH7ZSIJiclru5FdzArsBK9v2s4xkZpay5p9xxkPiabDzSugPKqCNSdbvia71rDm46v6q7JMTubMufvMg/0?wx_fmt=jpeg
    title: 环境学院第五届模拟联合国环境大会来啦!
    url: https://mp.weixin.qq.com/s/gq6Pvt2l2I2Fxp24T00smQ

  - cover: http://mmbiz.qpic.cn/mmbiz_jpg/IiaBlQyAP0uH7ZSIJiclru5FdzArsBK9v2zAej4PIA7qOXuwTX65ptMqeXiahZO1HddIEOO4KEl25HqLcyhCcPWfw/0?wx_fmt=jpeg
    title: 环境学院举办 2021 年秋季学期团校暨团学骨干素质提升工程(第一期)
    url: https://mp.weixin.qq.com/s/-mf1uDIXiaSA1mvLhTEv2A

  - cover: http://mmbiz.qpic.cn/mmbiz_jpg/IiaBlQyAP0uH7ZSIJiclru5FdzArsBK9v2LYJXttec0nI69XvicWX5UReyvW2cfZrSjPu4gBBvIZKWqibdnyXYa30A/0?wx_fmt=jpeg
    title: 青学沙龙(第 27 期)——“声声入耳，事事关心”主题活动
    url: https://mp.weixin.qq.com/s/HYg6f3aKRXh22gbzlK2vqA

  - cover: http://mmbiz.qpic.cn/mmbiz_jpg/IiaBlQyAP0uFdkUPSjWBrk8Y8CjfkNN4gk2Z2GjCRTbOEColNcpJ8ERAq0vrIyWyKcsLnqwjtIH8Hdla1ZOiaxkQ/0?wx_fmt=jpeg
    title: |-
      青年大学习·一起学党史: 百年光辉 | 中国共产党的发展
    url: https://mp.weixin.qq.com/s/56i0AN51JIMzxoCSLt5DdQ

  - cover: http://mmbiz.qpic.cn/mmbiz_jpg/IiaBlQyAP0uGgQjmiaD7PL2Cvm8DWYMhjWzKVRvsMqsVmndoo80T5xhibvBiaWfYZkrblGl8fJbCVxP8pAMLMnPQXw/0?wx_fmt=jpeg
    title: 环境学院第四届趣味运动会顺利举办!
    desc: 快来看看大家的精彩表现吧~
    url: https://mp.weixin.qq.com/s/JVMaGWzokao83ZSPEuN8zg

  - cover: http://mmbiz.qpic.cn/mmbiz_jpg/IiaBlQyAP0uEEO9oGqbxNLlCdS2fLou0cyWjnQWDvicicibnBDlFb3ZLlkXDxSPsrrzDdot7KRZLc6t9ePD7iac2H9w/0?wx_fmt=jpeg
    title: 科研达人成长训练营之专利撰写培训会
    url: https://mp.weixin.qq.com/s/TtSueDTMl36koQOI8cVM4Q

  - cover: http://mmbiz.qpic.cn/mmbiz_jpg/IiaBlQyAP0uEB8S1UVVh9MSWtw3WVgmqWgQCfVHNoFsu9zWaIFa9WvYlQLtIA2cd5RhyMZtxERWRBXPvgQFnDIg/0?wx_fmt=jpeg
    title: 环境学院 2021 年科研达人成长训练营之科研立项分享会
    url: https://mp.weixin.qq.com/s/3H-pAHT-G3c7h4IZ52KkQw

  - cover: http://mmbiz.qpic.cn/mmbiz_jpg/IiaBlQyAP0uEOOvcLz088HicbntEGpx2UvPOxlT7QIhGbURPUPKu2AibgCBcHO52rhUEOBTtwGSCrphDib9Buu9V7Q/0?wx_fmt=jpeg
    title: 书韵|老师陪你读书(第十一期)
    desc: 茶余饭后，一本好书，就是一段美好的时光。今天，让我们跟随李振新老师一起，走进《植物生理学》。
    url: https://mp.weixin.qq.com/s/bmKiJtTvSeuumdBUwx8FZA

  - cover: http://mmbiz.qpic.cn/mmbiz_jpg/IiaBlQyAP0uEvsrWiaAvgf8XGvlJmd0DPDKRs0x4X8GncTFftjqyclKL8657MictHaOqeQQH5L4pNWwZcFJDHibKGQ/0?wx_fmt=jpeg
    title: 花团锦簇，筑梦未来——环境学院少数民族风采展
    url: https://mp.weixin.qq.com/s/Wr8G_yL1dMdHpPuwsJyXKg

  - cover: http://mmbiz.qpic.cn/mmbiz_jpg/IiaBlQyAP0uEvsrWiaAvgf8XGvlJmd0DPDu4n5ILjlDibkZXVNcia7wa0YtJlIUQ9aWcKCtic5nYsKo6ickXGJQGMczw/0?wx_fmt=jpeg
    title: 环境学院 2020－2021 年度文明寝室评选
    url: https://mp.weixin.qq.com/s/8CmHr9CXiZa-sYW6Mo6fAg

  - cover: http://mmbiz.qpic.cn/mmbiz_jpg/IiaBlQyAP0uGvYm6GkOPKheOFlRkfhqBxs265IEMUrc2MSticcsGniayIsX8MGkjsptq7Cg8GibPwghJh82MjeTUYg/0?wx_fmt=jpeg
    title: 环院快讯丨“影映经典，乐学国庆”活动
    url: https://mp.weixin.qq.com/s/VP--oOlEtSX_w82cfCAWUg

  - cover: http://mmbiz.qpic.cn/mmbiz_jpg/IiaBlQyAP0uEsXgFJgVbDx3YVCPr4I511iaNjzNK0S4n3LuYE5fF5FSwHWvVchsORjicLmhUAZyyFRTpArATemWeQ/0?wx_fmt=jpeg
    title: 喜报丨我院 4 个项目荣获第五届中国青年志愿服务公益创业赛吉林省银奖、铜奖
    url: https://mp.weixin.qq.com/s/OkpyS3NluEhF0Rdst9WC7w

  - cover: http://mmbiz.qpic.cn/mmbiz_jpg/IiaBlQyAP0uFumGuI0nf7CE6xIapCeTdiaGrsYuKnjrM8g8lj7mNXC6iaK4uRVwhcktKhIu39PNamchIgmz1icnIzw/0?wx_fmt=jpeg
    title: “勿忘‘九·一八’，我辈当自强”主题演讲比赛
    desc: 一起来看看大家的精彩表现吧!
    url: https://mp.weixin.qq.com/s/fjwQCoWuFwJUiQ8VgdS_QA

  - cover: http://mmbiz.qpic.cn/mmbiz_jpg/IiaBlQyAP0uEbtPBD1IJicMRyXvwgwxiazKaTnadqt3ic9C6PicT1Aia9FvaVDSh8PBktueKOKY08TZ9K9WxDnH1wibqw/0?wx_fmt=jpeg
    title: 青学沙龙(Ⅰ)——“铭记历史，吾辈自强”研讨分享活动
    desc: 青马举办“铭记历史，吾辈自强”研讨分享活动，进来看看吧~
    url: https://mp.weixin.qq.com/s/P58MaQp-2us6PZCc7dOFZA

  - cover: http://mmbiz.qpic.cn/mmbiz_jpg/IiaBlQyAP0uGFiaSh1EQemUaEia1BrVoF20Yzj3px7ZxYHbMmfQ7RcwyicibqH87Haz2KBlORwpBzVTASwZC2BhsicRg/0?wx_fmt=jpeg
    title: 环院快讯 | “我为同学做件事”暨新生“传帮带”活动圆满结束!
    desc: 传帮带活动圆满结束啦! 一起来回顾一下吧~
    url: https://mp.weixin.qq.com/s/1KL9T0Q-YGAFSzHiE-AAiQ

  - cover: http://mmbiz.qpic.cn/mmbiz_jpg/IiaBlQyAP0uGVfdvDMTzyHichOn76fuV6LXTTOW1SgXD4ibvCOCBd7d5qRM4Cke8ErPfzmzNpHXDVMXs1kTGyrYiaQ/0?wx_fmt=jpeg
    title: 东北师范大学环境学院研究生招生特辑
    desc: 热烈欢迎 2022 届优秀本科毕业生来我院攻读研究生。
    url: https://mp.weixin.qq.com/s/CgU5-AFGVOr1DDQL6S4Pyw

  - cover: http://mmbiz.qpic.cn/mmbiz_jpg/IiaBlQyAP0uH2fic0w5f6IuA3vghoWkZMJkldF1r09nhJEQYV8vsdBiau9jgkJahgt6l5Bjciay5wx7TIOvADuqdag/0?wx_fmt=jpeg
    title: 勿忘国耻，兴我华夏
    desc: 九一八，不可忘却的纪念
    url: https://mp.weixin.qq.com/s/BB0SmJzVZmZ2qOuuQtccGg

  - cover: http://mmbiz.qpic.cn/mmbiz_jpg/IiaBlQyAP0uE7g4iaWLhjU44gh62oTASaqGtvduEIMY6Dt81O86of1vDvKpYzLrcZFCAE7KKl9BsADEgN6DTVO6Q/0?wx_fmt=jpeg
    title: 迎新特辑|八方来客，相约九月
    desc: 欢迎 2021 级的小伙伴们~
    url: https://mp.weixin.qq.com/s/kSNG-SM5X_PY-EugVa7aqw

  - cover: http://mmbiz.qpic.cn/mmbiz_jpg/IiaBlQyAP0uFGRrwFaBr44cTXZmWicukAhicmzxSmTKchhpJicicIsyMQ879VcJP9pYXFx4c8xap0923KfKCEO3fhoA/0?wx_fmt=jpeg
    title: 环境学院丨团学组织介绍(一)
    desc: 团学组织介绍之研究生会、学生会，快来一起了解吧~
    url: https://mp.weixin.qq.com/s/GLWZ9FJ-soBCcD9MsZJ4Uw

  - cover: http://mmbiz.qpic.cn/mmbiz_jpg/IiaBlQyAP0uEiaWTAtAjxYI7lyWH4WJuEAbrRckKJXjziaKZ7QzuickFLxroNVtaB1EySasFURicAajiciaIpFl8r1aHw/0?wx_fmt=jpeg
    title: 新生特辑(三) | 开学季攻略之学习系列
    url: https://mp.weixin.qq.com/s/3OprubxzvNS66Tkbm81BIg

  - cover: http://mmbiz.qpic.cn/mmbiz_jpg/IiaBlQyAP0uHGpb4zavl03LN5KjlVv4eJloSWVU8l2l4LeuT7pEwkKlCiasaZkMNA1JgJgkTw9ngWIQg5DlklTvg/0?wx_fmt=jpeg
    title: 新生特辑(二)|开学季攻略之生活系列
    url: https://mp.weixin.qq.com/s/SFSx26Sn7fW3t1cUkJisww

  - cover: http://mmbiz.qpic.cn/mmbiz_jpg/IiaBlQyAP0uFvPXX45oBCUpoticgUaYZibwDxVmMuJ6R0FdRuA4HWrBFjqGgJ3uy16bWr3vScq0ClH4LzAiaPxzWMw/0?wx_fmt=jpeg
    title: 新生特辑(一)|相遇东师环境
    desc: 环境学院的小萌新们快来看看吧~
    url: https://mp.weixin.qq.com/s/RTU86Z_QAzjRvSJamp4wpg

  - cover: http://mmbiz.qpic.cn/mmbiz_jpg/IiaBlQyAP0uFlO3mSicLZuTFgnjeFKFVCRab7QSed1iaJAnaKFvbARia0ECXJKicnL7GoqFAPHKeIH4fsyic03ibwFCzg/0?wx_fmt=jpeg
    title: 喜报 | 我院在 2021 年吉林省大学生马克思主义自学组织联盟社会实践活动暨吉林省大学生“三下乡”活动中取得优异成绩
    url: https://mp.weixin.qq.com/s/x8VQkvGzNyixZkTZUaehhA

  - cover: http://mmbiz.qpic.cn/mmbiz_jpg/IiaBlQyAP0uFnSic76QE8vnwjfQjTvkFia2ZZ2HH5BE9BKLZazuv7LpyEViaibNFicoXbG6x9sDRsqysHw5MLcHnHicXA/0?wx_fmt=jpeg
    title: 环境学院 2020 年度科研项目结项评审会成功举办
    url: https://mp.weixin.qq.com/s/88UiSK6jlcBhKcObWrX-aA

  - cover: http://mmbiz.qpic.cn/mmbiz_jpg/IiaBlQyAP0uFnSic76QE8vnwjfQjTvkFia2ApcvtYt7M5c7LicaibKMEicIlNPrScVfwQz3uicIStOv3wHiazkPWsyMc9w/0?wx_fmt=jpeg
    title: 环境学院 2021 年度科研项目中期评审会成功举办
    url: https://mp.weixin.qq.com/s/ReeUDPqTmsm5cQWG0n7ocQ

  - cover: http://mmbiz.qpic.cn/mmbiz_jpg/IiaBlQyAP0uEDpMRbkJ4FUiap42ntjOvTibZWNJFP3v1Q4GCibnF9Dajy14HruC8Pmnp2fd2vK1T9uhbloiczLtyY1g/0?wx_fmt=jpeg
    title: “环保在行动”绿色寝室创建活动之“绿色寝室秀”评比
    url: https://mp.weixin.qq.com/s/sRnIfhY6i_LetWEt5ZO2kg

  - cover: http://mmbiz.qpic.cn/mmbiz_jpg/IiaBlQyAP0uF82vkhW5rXGWe1YaHI2SpicIr6XNKgOJYFJuY6ZQZFp5tlc4eVORxTj1FZy05Q4IibptqymT6QEWAA/0?wx_fmt=jpeg
    title: 红歌合唱比赛|青春心向党，红歌齐飞扬
    url: https://mp.weixin.qq.com/s/kwZY8oL1r16l52vzkC2fGA

  - cover: http://mmbiz.qpic.cn/mmbiz_jpg/IiaBlQyAP0uF82vkhW5rXGWe1YaHI2SpicQGsLKt7ZepQFyvc1xOe1EPfFL1VgKjS8Gme5RRATp8w3kob3Ticy75w/0?wx_fmt=jpeg
    title: 5.25 心理文化节丨解忧信箱丨你可以写下心底的话，每一封都会有回信哦
    url: https://mp.weixin.qq.com/s/1n5C8G4GxbJcr2bc11rzOw

  - cover: http://mmbiz.qpic.cn/mmbiz_jpg/IiaBlQyAP0uF82vkhW5rXGWe1YaHI2Spicu5lQtMibRuRUZMdDyqeemIFEa9GZz65ZyedOZJKTibrymROT4DicwwAvA/0?wx_fmt=jpeg
    title: “科学实验战”实验技能大赛圆满结束
    url: https://mp.weixin.qq.com/s/WZUatnDyTv8oQa8BGAYnUg

  - cover: http://mmbiz.qpic.cn/mmbiz_jpg/IiaBlQyAP0uHZ7R7ymBUVvILueYQicyZyv1t4fibH3nF6iad2rgY0c1anlAgBiaJN8vRMLKKlAyiaeprFjmdmLaJsD3g/0?wx_fmt=jpeg
    title: 饮水之安，等你来见——第三届水科普大赛决赛来袭
    url: https://mp.weixin.qq.com/s/Xi9-jNapjy3RdbwSsaOY1g
