title: 东师介绍
id: intro
grey: true
hidden: true
content:
  - tag: grid
    header: 学校介绍
    items:
      - text: 学校概况
        color: red
        name: Description
        icon: about
        path: intro/about/

      - text: 学科建设
        color: olive
        name: Subject
        icon: content
        path: intro/subject/

      - text: 招生概况
        color: orange
        name: Enroll
        icon: enroll
        path: intro/enroll/

      - text: 学生就业
        color: cyan
        name: Job
        icon: job
        path: intro/job/

      - text: 资助
        color: purple
        name: Subsidize
        icon: subsidize
        path: intro/subsidize/

  # - tag: grid
  #   header: 学院介绍
  #   items:
  #     - text: 教育学部
  #       color: blue
  #       name: Education
  #       icon: education
  #       path: intro/school/education/

  #     - text: 心理学院
  #       color: orange
  #       name: Psychology
  #       icon: psychology
  #       path: intro/school/psychology/

  #     - text: 政法学院
  #       color: red
  #       name: Politics
  #       icon: politics
  #       path: intro/school/politics/

  #     - text: 经济与管理学院
  #       color: purple
  #       name: Economy
  #       icon: economy
  #       path: intro/school/economy/

  #     - text: 文学院
  #       color: cyan
  #       name: Chinese
  #       icon: chinese
  #       path: intro/school/chinese/

  #     - text: 历史文化学院
  #       color: olive
  #       name: History
  #       icon: history
  #       path: intro/school/history/

  #     - text: 外国语学院
  #       color: mauve
  #       name: Foreign
  #       icon: foreign
  #       path: intro/school/foreign/

  #     - text: 音乐学院
  #       color: blue
  #       name: Music
  #       icon: music
  #       path: intro/school/music/

  #     - text: 美术学院
  #       color: orange
  #       name: Art
  #       icon: art
  #       path: intro/school/art/

  #     - text: 马克思主义学部
  #       color: red
  #       name: Marx
  #       icon: marx
  #       path: intro/school/marx/

  #     - text: 数学与统计学院
  #       color: purple
  #       name: Math
  #       icon: math
  #       path: intro/school/math/

  #     - text: 信息科学与技术学院
  #       color: cyan
  #       name: Politic
  #       icon: ist
  #       path: intro/school/ist/

  #     - text: 物理学院
  #       color: olive
  #       name: Physics
  #       icon: physics
  #       path: intro/school/physics/

  #     - text: 化学学院
  #       color: mauve
  #       name: Chemistry
  #       icon: chemistry
  #       path: intro/school/chemistry/

  #     - text: 生命科学学院
  #       color: blue
  #       name: Biology
  #       icon: biology
  #       path: intro/school/biology/

  #     - text: 地理科学学院
  #       color: orange
  #       name: Geography
  #       icon: geography
  #       path: intro/school/geography/

  #     - text: 环境学院
  #       color: red
  #       name: Env
  #       icon: environment
  #       path: intro/school/environment/

  #     - text: 体育学院
  #       color: purple
  #       name: PE
  #       icon: basketball
  #       path: intro/school/pe/

  #     - text: 传媒科学学院
  #       color: cyan
  #       name: Media
  #       icon: media
  #       path: intro/school/media/
  #     - text: 国际汉学院
  #       color: mauve
  #       name: Internation
  #       icon: network
  #       path: intro/school/internation/

  #     # - text: 民族教育学院
  #     #   color: olive
  #     #   name: People
  #     #   icon: people
  #     #   path: intro/school/people/

  #     # - text: 纽瓦克学院
  #     #   color: blue
  #     #   name: Newark
  #     #   icon: school
  #     #   path: intro/school/newark/

  - tag: grid
    header: 机构介绍
    items:
      - text: 招生办公室
        color: orange
        name: Enroll
        icon: enroll
        path: intro/apt/enroll/

      - text: 研究生院
        color: grey
        name: Graduate
        icon: degree
        path: intro/apt/grad/

      - text: 党委学生工作部
        color: blue
        name: Student
        icon: student
        path: intro/apt/student/

      - text: 信息化办公室
        color: purple
        name: Information
        icon: pc
        path: intro/apt/xxhb/

      - text: 党委宣传部
        color: olive
        name: Publicize
        icon: league
        path: intro/apt/publicize/

      - text: 学生心理健康教育中心
        color: orange
        name: Psychology
        icon: psychology
        path: intro/apt/psychology/

      - text: 学校办公室
        color: red
        name: Office
        icon: office
        path: intro/apt/office/

      # - text: 校团委
      #   color: purple
      #   name: League
      #   icon: league
      #   path: intro/apt/youth-league/

      - text: 后勤管理处
        color: cyan
        name: Logistics
        icon: repair
        path: intro/apt/logistics/

      - text: 校医院
        color: olive
        name: Hospital
        icon: hospital
        path: intro/apt/hospital/

      - text: 保卫科
        color: mauve
        name: Defend
        icon: safe
        path: intro/apt/defend

      - text: 图书馆
        color: cyan
        name: Library
        icon: library
        path: intro/apt/library/

      - text: 教务处
        color: blue
        name: Course
        icon: jwc
        path: intro/apt/course/

      - text: 学生就业指导服务中心
        color: cyan
        name: Career
        icon: job
        path: intro/apt/career

      - text: 档案馆
        color: purple
        name: Archive
        icon: archive
        path: intro/apt/archive/

    footer: " "
