title: é¦–é¡µ
id: main
grey: true
hidden: true
content:
  - tag: card
    cover: $img/new-year.jpg
    title: è™å¹´ç¥è¯
    logo: https://mr.hope.site/logo.svg
    name: Mr. Hope
    url: page?path=Onew-year

  # - tag: title
  #   text: å¸Œæœ›å·¥ä½œå®¤é•¿æœŸæ‹›æ–°

  # - tag: list
  #   header: false
  #   items:
  #     - text: æ‹›æ–°è¯¦æƒ…
  #       url: page?path=Ohope-studio/invite

  # - tag: title
  #   text: æ­¤å¤„æœ‰æœç´¢ğŸ‘† æ‚¨å¯ä»¥å¯¹å°ç¨‹åºå†…å®¹è¿›è¡ŒæŸ¥æ‰¾

  - tag: grid
    header: æ‚¨å¯èƒ½æƒ³å…³æ³¨
    items:
      - text: æ ¡å†
        color: mauve
        name: Calendar
        icon: calendar
        url: calendar

      - text: ç«è½¦ç¥¨è´­ä¹°
        color: blue
        name: Ticket
        icon: train
        path: guide/traffic/train/

      - text: è¯¾ç¨‹
        color: orange
        name: Course
        icon: content
        path: guide/course/

      - text: æ•™åŠ¡ç³»ç»Ÿ
        color: red
        name: System
        icon: system
        path: guide/system/

      - text: å­¦ä¹ 
        color: mauve
        name: Study
        icon: study
        path: guide/study/

      - text: å›¾ä¹¦é¦†
        color: blue
        name: Library
        icon: library
        path: intro/apt/library/

      - text: æ ¡å†…è€ƒè¯•
        color: olive
        name: Test
        icon: test
        path: guide/test/

      - text: ç”Ÿæ´»
        color: olive
        name: Life
        icon: life
        path: guide/life/

    footer: æ›´å¤šå†…å®¹è¯·è¯¦è§ä¸‹æ–¹å…¶ä»– Tab é¡µ

  # - tag: card
  #   cover: http://mmbiz.qpic.cn/mmbiz_jpg/ic9k8LCTbicc7fibAYDFBn7oAvOaEs00iblrOKaFWoIrqzQzoXXDPmHNjS9bm9ZUVQWB3149EYsjmQNS4jU1HzUW5Q/0?wx_fmt=jpeg
  #   title: æ‹›çº³å°ç¨‹åºå¿—æ„¿è€…
  #   logo: $img/inNENU.png
  #   name: inä¸œå¸ˆ
  #   url: page?path=Oguide/volunteer
