title: é¦–é¡µ
id: main
grey: true
hidden: true
content:
  # - tag: title
  #   text: å¸Œæœ›å·¥ä½œå®¤é•¿æœŸæ‹›æ–°

  # - tag: list
  #   header: false
  #   content:
  #     - text: æ‹›æ–°è¯¦æƒ…
  #       url: page?path=other/hope-studio/invite

  # - tag: title
  #   text: æ­¤å¤„æœ‰æœç´¢ğŸ‘† æ‚¨å¯ä»¥å¯¹å°ç¨‹åºå†…å®¹è¿›è¡ŒæŸ¥æ‰¾

  - tag: card
    type: web
    src: http://mmbiz.qpic.cn/mmbiz_jpg/ic9k8LCTbicc4IJp1vBknfXts0OgyGesur3vUZEZhVAGM1KE8M48sWHKqGTyGXN9vhhecNnON6KUQVsFrmTSqyVA/0?wx_fmt=jpeg
    url: https://mp.weixin.qq.com/s/08NvcTE5L9e1HsyqOsJpKw
    title: å‘ç£ç‰ä¹¦æ³•ç¤¾çš„å…¬å¼€è‡´æ­‰
    logo: https://mp.innenu.com/img/inNENU.png
    name: inä¸œå¸ˆ

  - tag: grid
    header: æ‚¨å¯èƒ½æƒ³å…³æ³¨
    content:
      - text: å­¦è´¹ç¼´çº³
        color: orange
        name: Pay
        icon: money
        path: guide/check/pay/

      - text: å…¥å­¦æ´»åŠ¨
        color: purple
        name: Activity
        icon: activity
        path: guide/activity/

      - text: å¿«é€’
        color: mauve
        name: Express
        icon: express
        path: guide/express/

      - text: å¯å®¤
        color: grey
        name: Dorm
        icon: dorm
        path: guide/dorm/

      - text: é£Ÿå ‚
        color: mauve
        name: Dining
        icon: dining
        path: guide/dining/

      - text: è¶…å¸‚
        color: olive
        name: Shop
        icon: shop
        path: guide/shop/

      - text: æ´—æµ´
        color: red
        name: Bath
        icon: bath
        path: guide/bath/

      - text: ç”Ÿæ´»
        color: purple
        name: Life
        icon: life
        path: guide/life/

      - text: è´¦æˆ·
        color: blue
        name: Account
        icon: authorize
        path: guide/account/

      - text: æ ¡å›­å¡
        color: red
        name: Card
        icon: card
        path: guide/card/

      - text: æ ¡å›­ç½‘
        color: purple
        name: Network
        icon: network
        path: guide/network/

      - text: é€‰è¯¾
        color: cyan
        name: Select
        icon: select
        path: guide/select/

      # - text: ç–«æƒ…ç›¸å…³
      #   color: mauve
      #   name: Epidemic
      #   icon: virus
      #   path: guide/epidemic/

      # - text: æ¯æ—¥å¥åº·ä¸ŠæŠ¥
      #   color: purple
      #   name: Report
      #   icon: apply
      #   path: guide/epidemic/miniprogram/

      # - text: å…¥å­¦å‡†å¤‡
      #   color: red
      #   name: Prepare
      #   icon: prepare
      #   path: guide/prepare/

      # - text: éœ€å¸¦ç‰©å“
      #   color: olive
      #   name: Necessity
      #   icon: necessity
      #   path: guide/necessity/

      # - text: ä¸“ä¸šä»‹ç»
      #   color: olive
      #   name: Major
      #   icon: about
      #   path: intro/school/major

      # - text: å­¦æ ¡ä»‹ç»
      #   color: mauve
      #   name: Intro
      #   icon: about
      #   path: intro/about/

      # - text: è½¬ä¸“ä¸š
      #   color: orange
      #   name: Change Major
      #   icon: change
      #   path: guide/change-major/

      # - text: å­¦ä½
      #   color: blue
      #   name: Degree
      #   icon: degree
      #   path: guide/degree/

      # - text: æ–°ç”Ÿç¾¤
      #   color: purple
      #   name: QQ Group
      #   icon: qq-group
      #   path: guide/prepare/qq-group/

      # - text: è°¨é˜²è¯ˆéª—
      #   color: blue
      #   name: Protection
      #   icon: alert
      #   path: guide/prepare/cheat

    footer: æ›´å¤šå†…å®¹è¯·è¯¦è§ä¸‹æ–¹å…¶ä»– Tab é¡µ

  - tag: card
    src: http://mp.innenu.com/img/tab/map.jpg
    title: æ ¡å›­åœ°å›¾ä¸å¯¼èˆª
    logo: map
    url: map

  - tag: card
    src: http://mp.innenu.com/img/tab/faq.png
    title: å¸¸è§é—®é¢˜
    logo: faq
    url: page?id=guide/faq/
