title: é¦–é¡µ
id: main
grey: true
hidden: true
content:
  # - tag: title
  #   text: å¸Œæœ›å·¥ä½œå®¤é•¿æœŸæ‹›æ–°

  # - tag: list
  #   header: false
  #   content:
  #     - text: æ‹›æ–°è¯¦æƒ…
  #       url: page?path=other/hope-studio/invite

  - tag: title
    text: æ­¤å¤„æœ‰æœç´¢ğŸ‘† æ‚¨å¯ä»¥å¯¹å°ç¨‹åºå†…å®¹è¿›è¡ŒæŸ¥æ‰¾

  # - tag: ul
  #   type: warning
  #   text:
  #     - è¯·ä¸è¦å…³é—­èµ„æºæ›´æ–°ï¼Œå¦åˆ™æ‚¨å°†æ— æ³•è·å¾—å°ç¨‹åºæ¯æ—¥æ¨é€çš„æ–°å†…å®¹æˆ–æ›´æ­£ã€‚å¦‚æœæ‚¨å·²ç»å…³é—­ï¼Œå»ºè®®åœ¨â€œæˆ‘çš„ä¸œå¸ˆâ€é¡µé¢è¿›å…¥â€œå¤–è§‚è®¾ç½®â€å°†å…¶å¼€å¯ã€‚
  #     - å…³äºç–«æƒ…ä¸æŠ¥é“ç›¸å…³æ¶ˆæ¯ï¼Œè¯·å…³æ³¨å¹´çº§ç¾¤ä¸­è¾…å¯¼å‘˜çš„é€šçŸ¥ã€‚ç”±äºè¿™æ˜¯ä¸€ä¸ªä¸ªäººå°ç¨‹åºï¼Œå­¦æ ¡å¹¶ä¸ä¼šé€šçŸ¥ Mr.Hope æœ¬äººã€Mr.Hope éœ€è¦è‡ªè¡Œå…³æ³¨è¿™äº›æ¶ˆæ¯ï¼Œå¯¼è‡´å°ç¨‹åºå¯èƒ½å­˜åœ¨æ›´æ–°å»¶è¿Ÿã€‚

  # - tag: list
  #   header: ä½¿ç”¨å¿…è¯»
  #   content:
  #     - text: å°ç¨‹åºä½¿ç”¨é¡»çŸ¥
  #       icon: about
  #       url: page?path=other/about/guide

  - tag: grid
    header: æ‚¨å¯èƒ½æƒ³å…³æ³¨
    content:
      - text: å½•å–æŸ¥è¯¢
        color: orange
        name: Search
        icon: search
        path: intro/enroll/search

      - text: æ–°ç”Ÿå…¥å­¦æ•™è‚²
        color: blue
        name: Course
        icon: study
        path: guide/yiban/

      - text: æ¯æ—¥å¥åº·ä¸ŠæŠ¥
        color: purple
        name: Report
        icon: apply
        path: guide/epidemic/miniprogram/

      - text: å…¥å­¦å‡†å¤‡
        color: red
        name: Prepare
        icon: prepare
        path: guide/prepare/

      - text: ä¸“ä¸šä»‹ç»
        color: olive
        name: Major
        icon: about
        path: intro/school/major

      - text: å­¦æ ¡ä»‹ç»
        color: mauve
        name: Intro
        icon: about
        path: intro/about/

      - text: è½¬ä¸“ä¸š
        color: orange
        name: Change Major
        icon: change
        path: guide/change-major/

      - text: å­¦ä½
        color: blue
        name: Degree
        icon: degree
        path: guide/degree/

      - text: æ–°ç”Ÿç¾¤
        color: purple
        name: QQ Group
        icon: qq-group
        path: guide/prepare/qq-group/

      - text: è°¨é˜²è¯ˆéª—
        color: blue
        name: Protection
        icon: alert
        path: guide/prepare/cheat

      - text: å¯å®¤
        color: grey
        name: Dorm
        icon: dorm
        path: guide/dorm/

      - text: é£Ÿå ‚
        color: mauve
        name: Dining
        icon: dining
        path: guide/dining/

    footer: æ›´å¤šå†…å®¹è¯·è¯¦è§ä¸‹æ–¹å…¶ä»– Tab é¡µ
