- tag: text
  type: p
  text: 在此特别提醒您，在您通过校园统一身份登录使用本小程序“in 东师”、“东师青年+”(以下简称“本小程序”)，为小程序提供后端服务的远程服务器以下简称为“远程服务器”，小程序的宿主服务商以下简称为小程序服务商，本小程序和远程服务器的提供者(以下简称为“服务提供者”)之前、或者在您已经通过登录使用本小程序并決定继续使用小程序提供的服务之前，仔细阅读本协议的内容，确保您正确理解了本协议各条款的含义
- tag: text
  text: "请您审慎阋读本协议各条款。在您看到本协议时有以下两个情形:"
- tag: text
  text: "1. 如果您还未登录使用本小程序: 在此情形下您不接受并同意本协议所有条款，您将无权使用本小程序提供的所有服务。"
