- tag: list
  header: 小程序介绍
  content:
    - text: "   小程序全部内容均由 Mr.Hope 独立开发。"

    - text: "   小程序现有字数为 390520 字，其中东师介绍部分 177554 字，东师指南部分 161449 字，功能大厅部分 23965 字，其他部分 27552 字。"

    - text: Hope Studio 介绍
      url: page?path=other/hope-studio/about

    - text: Mr.Hope 个人介绍
      url: page?path=other/about/mrhope

    - text: 致谢名单
      url: page?path=other/about/thanks

- tag: list
  header: 内容版权及使用
  content:
    - text: "   请您特别注意，除标注来源的文字、图片 Mr.Hope 没有版权外，其余文字、图片均放置在 “署名 - 非商业性使用 - 禁止演绎 4.0 国际许可证” 下。请您合法使用这些文字与图片，以避免遭到 Mr.Hope 的起诉。"

    - text: 协议详情
      url: page?path=other/about/copyright
