title: 东师介绍
id: intro
grey: true
hidden: true
content:
  - tag: grid
    header: 学校介绍
    content:
      - text: 学校概况
        color: red
        name: Description
        icon: about
        path: intro/about/

      - text: 招生概况
        color: orange
        name: Enroll
        icon: enroll
        path: intro/enroll/

      - text: 资助
        color: purple
        name: Subsidize
        icon: subsidize
        path: intro/subsidize/

  - tag: grid
    header: 学院介绍
    content:
      - text: 教育学部
        color: blue
        name: Education
        icon: education
        path: intro/school/education/

      - text: 心理学院
        color: orange
        name: Psychology
        icon: psychology
        path: intro/school/psychology/

      - text: 政法学院
        color: red
        name: Politics
        icon: politics
        path: intro/school/politics/

      - text: 经济与管理学院
        color: purple
        name: Economy
        icon: economy
        path: intro/school/economy/

      - text: 文学院
        color: cyan
        name: Chinese
        icon: chinese
        path: intro/school/chinese/

      - text: 历史文化学院
        color: olive
        name: History
        icon: history
        path: intro/school/history/

      - text: 外国语学院
        color: mauve
        name: Foreign
        icon: foreign
        path: intro/school/foreign/

      - text: 音乐学院
        color: blue
        name: Music
        icon: music
        path: intro/school/music/

      - text: 美术学院
        color: orange
        name: Art
        icon: art
        path: intro/school/art/

      - text: 马克思主义学部
        color: red
        name: Marx
        icon: marx
        path: intro/school/marx/

      - text: 数学与统计学院
        color: purple
        name: Math
        icon: math
        path: intro/school/math/

      - text: 信息科学与技术学院
        color: cyan
        name: Politic
        icon: ist
        path: intro/school/ist/

      - text: 物理学院
        color: olive
        name: Physics
        icon: physics
        path: intro/school/physics/

      - text: 化学学院
        color: mauve
        name: Chemistry
        icon: chemistry
        path: intro/school/chemistry/

      - text: 生命科学学院
        color: blue
        name: Biology
        icon: biology
        path: intro/school/biology/

      - text: 地理科学学院
        color: orange
        name: Geography
        icon: geography
        path: intro/school/geography/

      - text: 环境学院
        color: red
        name: Env
        icon: environment
        path: intro/school/environment/

      - text: 体育学院
        color: purple
        name: PE
        icon: basketball
        path: intro/school/pe/

      - text: 传媒科学学院
        color: cyan
        name: Media
        icon: media
        path: intro/school/media/

      - text: 民族教育学院
        color: olive
        name: People
        icon: people
        path: intro/school/people/

      - text: 国际汉学院
        color: mauve
        name: Internation
        icon: network
        path: intro/school/internation/

      - text: 纽瓦克学院
        color: blue
        name: Newark
        icon: school
        path: intro/school/newark/

  - tag: grid
    header: 机构介绍
    content:
      - text: 党委学生工作部
        color: blue
        name: Student
        icon: student
        path: intro/apartment/student/

      - text: 党委宣传部
        color: olive
        name: Publicize
        icon: league
        path: intro/apartment/publicize/

      - text: 学生心理健康教育中心
        color: orange
        name: Psychology
        icon: psychology
        path: intro/apartment/psychology/

      - text: 学校办公室
        color: red
        name: Office
        icon: office
        path: intro/apartment/office/

      - text: 校团委
        color: purple
        name: League
        icon: league
        path: intro/apartment/youth-league/

      - text: 后勤管理处
        color: cyan
        name: Logistics
        icon: wrench
        path: intro/apartment/logistics/

      - text: 校医院
        color: olive
        name: Hospital
        icon: hospital
        path: intro/apartment/hospital/

      - text: 保卫科
        color: mauve
        name: Defend
        icon: safe
        path: intro/apartment/defend

      - text: 图书馆
        color: cyan
        name: Library
        icon: library
        path: intro/apartment/library/

      - text: 教务处
        color: blue
        name: Course
        icon: jwc
        path: intro/apartment/course/

      - text: 学生就业指导服务中心
        color: cyan
        name: Career
        icon: job
        path: intro/apartment/career

    footer: " "
