title: é¦–é¡µ
id: main
grey: true
hidden: true
content:
  # - tag: title
  #   text: å¸Œæœ›å·¥ä½œå®¤é•¿æœŸæ‹›æ–°

  # - tag: list
  #   header: false
  #   content:
  #     - text: æ‹›æ–°è¯¦æƒ…
  #       url: page?path=other/hope-studio/invite

  # - tag: title
  #   text: æ­¤å¤„æœ‰æœç´¢ğŸ‘† æ‚¨å¯ä»¥å¯¹å°ç¨‹åºå†…å®¹è¿›è¡ŒæŸ¥æ‰¾

  - tag: card
    cover: http://mmbiz.qpic.cn/mmbiz_jpg/ic9k8LCTbicc7fibAYDFBn7oAvOaEs00iblrOKaFWoIrqzQzoXXDPmHNjS9bm9ZUVQWB3149EYsjmQNS4jU1HzUW5Q/0?wx_fmt=jpeg
    title: æ‹›çº³å°ç¨‹åºå¿—æ„¿è€…
    logo: https://mp.innenu.com/img/inNENU.png
    name: inä¸œå¸ˆ
    url: web?url=https://mp.weixin.qq.com/s/smstzxKp_YEmeRYNFPd-Kw

  - tag: grid
    header: æ‚¨å¯èƒ½æƒ³å…³æ³¨
    content:
      - text: å­¦ç”Ÿç»„ç»‡
        color: blue
        name: Orgnazation
        icon: student-org
        path: guide/organization/

      - text: ç¤¾å›¢
        color: orange
        name: Association
        icon: association
        path: guide/association/

      - text: å…¥å­¦æ´»åŠ¨
        color: purple
        name: Activity
        icon: activity
        path: guide/activity/

      - text: ç”Ÿæ´»
        color: olive
        name: Life
        icon: life
        path: guide/life/

    footer: æ›´å¤šå†…å®¹è¯·è¯¦è§ä¸‹æ–¹å…¶ä»– Tab é¡µ
